name: main

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Build
        run: |
          version=`git describe --tags`
          npm i
          npm run build
          cd dist
          zip -r headscale-ui-${{ github.ref_name }}.zip headscale-ui
      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.ReleaseVersion }}
          title: ${{ env.ReleaseVersion }}
          prerelease: false
          files: |
            dist/headscale-ui-${{ github.ref_name }}.zip

      - name: Create Docker File
        run: |
          echo "FROM nginx:alpine" > Dockerfile
          echo "COPY dist/headscale-ui /usr/share/nginx/html/manager" >> Dockerfile
          echo "WORKDIR /usr/share/nginx/html/" >> Dockerfile
          pwd
          cat Dockerfile
